# Generated by Django 3.1.2 on 2024-06-12 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='food_additional_desctiption',
            new_name='food_additional_description',
        ),
    ]
