# Generated by Django 3.1.2 on 2024-07-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20240625_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='ingredient_description_first',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='ingredient_description_second',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='ingredient_description_third',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
