# Generated by Django 5.0.7 on 2024-07-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_food_id_alter_ingredient_id_alter_userfood_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useringredient',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
