# Generated by Django 5.0.7 on 2024-07-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_useringredient_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useringredient',
            name='quantity',
        ),
    ]
