# Generated by Django 3.2.25 on 2024-07-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_remove_useringredient_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_id', models.IntegerField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
